/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 7;
  /** RegularExpression Id. */
  int POSDIGIT = 8;
  /** RegularExpression Id. */
  int ZERO = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int KEYWORD = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int OPEN = 13;
  /** RegularExpression Id. */
  int CLOSE = 14;
  /** RegularExpression Id. */
  int IDENT = 15;
  /** RegularExpression Id. */
  int LETTER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<KEYWORD>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<IDENT>",
    "<LETTER>",
  };

}
